services:
        rabbitmq:
               image: rabbitmq:3-management
               container_name: rabbitmq_management
               
               ports: 
                - 5672:5672 # (erlang) 
                - 15672:15672 # communication with the web management API 
               
        #        volumes:
                # data persistence
                # - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
                # - /docker_conf/rabbitmq/data/log_rabbitmq_management:/var/lib/rabbitmq/
                # data mapping -> host: container
                # queues and messages data of the container will be stored on the host
               environment:
                - RABBITMQ_DEFAULT_USER=guest
                - RABBITMQ_DEFAULT_PASS=guest

               restart: always
